export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const COLOR_REQUEST = 'COLOR_REQUEST';
export const RECEIVE_COLORS = 'RECEIVE_COLORS';
export const SEARCH_CRITERIA_CHANGED = 'SEARCH_CRITERIA_CHANGED';
